# Generated by Django 5.1.1 on 2024-09-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years_of_experience', models.IntegerField(max_length=5)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_id', to='employee.position')),
            ],
        ),
    ]
